/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    System.out.println(new Calculate().sum_roop(2, 3));
    System.out.println(new Calculate().average(2, 3));
  }
}
